############################################################
# Dockerfile to build PiHole Container Image
# based on Original PiHole Image
############################################################
# Container pihole
############################################################

# Set the base Image
FROM pihole/pihole:4.0.0-1_armhf

# File Author / Maintainer
MAINTAINER Sven Berger

COPY ./scripte/entrypoint.sh /entrypoints/pihole.sh