############################################################
# Dockerfile to build Proxy Image
# bases on linuxserver.io/letsencrypt
############################################################
# Container APP für Proxy Server mit Letsencrypt
############################################################

# Set the base Image
FROM lsioarmhf/letsencrypt:latest

# File Author / Maintainer
MAINTAINER Sven Berger
