############################################################
# Dockerfile to build Organizr Container Image
# based on Linuxserver Organizr Image
############################################################
# Container organizr
############################################################

# Set the base Image
FROM lsiocommunity/organizr:latest

# File Author / Maintainer
MAINTAINER Sven Berger
