############################################################
# Dockerfile to build Git Gogs Container Image
# based on Original gogs Image
############################################################
# Container gogs
############################################################

# Set the base Image
FROM gogs/gogs:latest

# File Author / Maintainer
MAINTAINER Sven Berger

