############################################################
# Dockerfile to build Portainer Container Image
# based on Original portainer Image
############################################################
# Container Portainer
############################################################

# Set the base Image
FROM portainer/portainer:linux-amd64

# File Author / Maintainer
MAINTAINER Sven Berger

# Zusätzliche Befehle
